<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DcaShop.Inventory</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../DcaShop.SharedKernel/DcaShop.SharedKernel.csproj" />
  </ItemGroup>
</Project>
