<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/DcaShop.Account/DcaShop.Account.csproj" />
    <ProjectReference Include="../../src/DcaShop.Product/DcaShop.Product.csproj" />
    <ProjectReference Include="../../src/DcaShop.Cart/DcaShop.Cart.csproj" />
    <ProjectReference Include="../../src/DcaShop.Checkout/DcaShop.Checkout.csproj" />
  </ItemGroup>
</Project>
