# Parent-directory context: admit only the two directories the build reads
*
!dca-dotnet/Directory.Build.props
!dca-dotnet/global.json
!dca-dotnet/branding
!dca-dotnet/src
!dca-ecommerce-sample-dotnet/DcaShop.sln
!dca-ecommerce-sample-dotnet/Directory.Build.props
!dca-ecommerce-sample-dotnet/global.json
!dca-ecommerce-sample-dotnet/src
**/bin
**/obj
**/.git
