<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DcaShop.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../DcaShop.SharedKernel/DcaShop.SharedKernel.csproj" />
    <ProjectReference Include="../DcaShop.Pricing/DcaShop.Pricing.csproj" />
    <ProjectReference Include="../DcaShop.Inventory/DcaShop.Inventory.csproj" />
    <ProjectReference Include="../DcaShop.Product/DcaShop.Product.csproj" />
    <ProjectReference Include="../DcaShop.Account/DcaShop.Account.csproj" />
    <ProjectReference Include="../DcaShop.Cart/DcaShop.Cart.csproj" />
    <ProjectReference Include="../DcaShop.Portal/DcaShop.Portal.csproj" />
    <ProjectReference Include="../DcaShop.Checkout/DcaShop.Checkout.csproj" />
  </ItemGroup>
</Project>
