<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DcaShop.Product</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../DcaShop.SharedKernel/DcaShop.SharedKernel.csproj" />
    <ProjectReference Include="../DcaShop.Pricing/DcaShop.Pricing.csproj" />
    <ProjectReference Include="../DcaShop.Inventory/DcaShop.Inventory.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
  </ItemGroup>
</Project>
