<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DcaShop.Checkout</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../DcaShop.SharedKernel/DcaShop.SharedKernel.csproj" />
    <ProjectReference Include="../DcaShop.Product/DcaShop.Product.csproj" />
    <ProjectReference Include="../DcaShop.Cart/DcaShop.Cart.csproj" />
    <ProjectReference Include="../DcaShop.Inventory/DcaShop.Inventory.csproj" />
  </ItemGroup>
</Project>
